QLKS_CNPM_LT/Controllers/PhongController.cs
using QLKS_CNPM_LT.Models;
using QLKS_CNPM_LT.Models.Function;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;

namespace QLKS_CNPM_LT.Controllers
{
    public class PhongController : Controller
    {
        // GET: Phong
        private qlks_CNPMEntities db = new qlks_CNPMEntities();
        public ActionResult DSPhong()
        {
            var func_phong = new Phong_Func();
            return View(func_phong.toanBoPhong());
        }


        public ActionResult CTlOAIPhong()
        {

            ViewBag.Success = 0;
            string id = (string)RouteData.Values["id"];
            LOAIPHONG lp = db.LOAIPHONGs.Find(id);
            if (lp == null)
            {
                return View(new List<PHONG>());
            }
            ViewBag.Success = 1;
            ViewBag.TenLoai = lp.TenLoai;
            ViewBag.DuongDanAnh = lp.DuongDanAnh;
            ViewBag.GhiChu = lp.GhiChu;
            var listPhong = db.PHONGs.Where(m => m.MaLoai == id).ToList();
            return View(listPhong);
        }

        public ActionResult DatPhong()
        {
            if (Session["TaiKhoan"] == null)
            {
                Session["TrangTruoc"] = Request.RawUrl;
                return RedirectToAction("DangNhap", "CaNhan");
            }

            string MaPhong = (string)RouteData.Values["id"];
            var phong = db.PHONGs.Where(m => m.MA_PHONG == MaPhong).First();
            var loaiPhong = db.LOAIPHONGs.Where(m => m.MaLoai == phong.MaLoai).First();
            ViewBag.DuongDanAnh = loaiPhong.DuongDanAnh;
            ViewBag.TenLoai = loaiPhong.TenLoai;
            return View(phong);
        }


    }
}

QLKS_CNPM_LT/Views/Shared/HouseLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abel Feel like home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script defer src="~/Scripts/Myjs/AnimationIn.js"></script>
    <link rel="stylesheet" href="~/Content/Mystyle/Main.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>
    <div class="Container">

        <div class="Header" id="Header" style="background:rgba(0,0,0,.7)">
            <span href="" class="logo">
                <img src="~/Content/images/Abel.png" />
            </span>



            <div id="Menu">
                <div class="item">
                    <a class="none" href="/Home/Home">TRANG CHỦ</a>
                </div>
                <div class="item">
                    <div class="dropdown">
                        <a class="none" href="/Phong/DSPhong">DANH SÁCH PHÒNG</a>
                        <div class="dropdown-content">
                            <div class="_column">
                                @*@{Html.RenderAction("LoaiPhongPartial", "Phong");}*@
                            </div>
                        </div>
                    </div>


                </div>
                <div class="item">
                    <a class="none" href="#footer">LIÊN HỆ</a>
                </div>
                <div class="item">
                    <a class="none" href="/OrderDetail/Top5">TOP SẢN PHẨM BÁN CHẠY</a>
                </div>
            </div>





            <div id="Action">
                @if (Session["FullName"] == null && Session["Admin"] == null)
                {
                    <div class="item">
                        <div class="dropdown">
                            <button class="dropbtn"><i class="fa fa-user"></i></button>
                            <div class="dropdown-content_user" style="left:0;">
                                <a href="/Admin/Admin"><ion-icon name="log-in-outline"></ion-icon> Đăng nhập Admin</a>
                                <a href="/LoginUser/Index"><ion-icon name="log-in-outline"></ion-icon> Đăng nhập</a>
                                <a href="/LoginUser/RegisterUser"><ion-icon name="person-add-outline"></ion-icon> Đăng ký</a>
                            </div>
                        </div>
                    </div>
                }
                else if (Session["Admin"] != null)
                {
                    <div class="item">
                        <div class="dropdown">
                            <button class="dropbtn">Hello @Session["Admin"]</button>
                            <div class="dropdown-content_user" style="left:0;">
                                <a href="@Url.Action("Index","Product")">Tạo sản phẩm</a>
                                <a href="@Url.Action("Index","Categories")">Tạo loại sản phẩm</a>
                                <a href="@Url.Action("Index","OrderProes")">Thông tin các khách hàng</a>
                                <a href="@Url.Action("Index","OrderDetails2")">Danh sách sản phẩm khách hàng đặt</a>
                                <a href="@Url.Action("LogOutUser","Admin")"><ion-icon name="log-out-outline"></ion-icon>Đăng suất</a>
                            </div>
                        </div>
                    </div>
                }

                else
                {
                    <div class="item">
                        <div class="dropdown">
                            <button class="dropbtn">Hello @Session["FullName"]</button>
                            <div class="dropdown-content_user" style="left:0;">
                                <a href="@Url.Action("LogOutUser","LoginUser")"><ion-icon name="log-out-outline"></ion-icon>Đăng suất</a>
                            </div>
                        </div>
                    </div>
                }
                <div class="item">
                    @*<a href="/ShoppingCart/ShowCart"><ion-icon name="cart-outline"></ion-icon> Giỏ hàng @Html.Action("BagCart", "ShoppingCart")   </a>*@
                </div>



            </div>


        </div>

        <div id="Products">
            @RenderBody()
        </div>




        <div id="footer" class="myhidden">
            <div class="box">
                <div class="logo">
                    <img src="~/Content/images/logo-remov.png" alt="">
                    <p></p>
                </div>
            </div>

            <div class="box">
                <h3>NỘI DUNG</h3>
                <ul class="quick-menu">
                    <div class="item">
                        <p>Nguyễn Hoàng Thịnh Khang <span style="color:gold">[Leader]</span></p>
                        <p>Nguyễn Bảo Duyên <span style="color:lightpink">[Mem]</span></p>
                        <p>Trần văn Minh <span style="color:aqua">[Mem]</span></p>
                    </div>
                </ul>
            </div>


        </div>

    </div>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/Scripts/MyJs/MyJs.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

QLKS_CNPM_LT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abel Feel like home</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="~/Content/Mystyle/Main.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>
<body>

    <div class="Container">


        <div class="Header" id="Header">
            <span href="" class="logo ">
                <img src="~/Content/images/Abel.png" />
            </span>



            <div id="Menu">
                <div class="item ">
                    <a class="none" href="/Home/Home">TRANG CHỦ</a>
                </div>
                <div class="item">
                    <div class="dropdown">
                        <a class="none" href="/Phong/DSPhong">DANH SÁCH PHÒNG</a>
                        <div class="dropdown-content">
                            <div class="_column">
                                @* @{Html.RenderAction("CategoryPartial", "Categories");}   *@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <a class="none" href="#footer">LIÊN HỆ</a>
                </div>
                <div class="item">
                    <a class="none" href="/OrderDetail/Top5">TOP SẢN PHẨM BÁN CHẠY</a>
                </div>
            </div>





            <div id="Action">
                @if (Session["FullName"] == null && Session["Admin"] == null)
                {
                    <div class="item">
                        <div class="dropdown">
                            <span class="dropbtn"><i class="fa fa-user"></i></span>
                            <div class="dropdown-content_user" style="left:0;">
                                <a href="/Admin/Admin"><ion-icon name="log-in-outline"></ion-icon> Đăng nhập Admin</a>
                                <a href="/LoginUser/Index"><ion-icon name="log-in-outline"></ion-icon> Đăng nhập</a>
                                <a href="/LoginUser/RegisterUser"><ion-icon name="person-add-outline"></ion-icon> Đăng ký</a>
                            </div>
                        </div>
                    </div>
                }
                else if (Session["Admin"] != null)
                {
                    <div class="item">
                        <div class="dropdown">
                            <button class="dropbtn">Hello @Session["Admin"]</button>
                            <div class="dropdown-content_user" style="left:0;">
                                <a href="@Url.Action("Index","Product")">Tạo sản phẩm</a>
                                <a href="@Url.Action("Index","Categories")">Tạo loại sản phẩm</a>
                                <a href="@Url.Action("Index","OrderProes")">Thông tin các khách hàng</a>
                                <a href="@Url.Action("Index","OrderDetails2")">Danh sách sản phẩm khách hàng đặt</a>
                                <a href="@Url.Action("LogOutUser","Admin")"><ion-icon name="log-out-outline"></ion-icon>Đăng suất</a>
                            </div>
                        </div>
                    </div>
                }

                else
                {
                    <div class="item">
                        <div class="dropdown">
                            <button class="dropbtn">Hello @Session["FullName"]</button>
                            <div class="dropdown-content_user" style="left:0;">
                                <a href="@Url.Action("LogOutUser","LoginUser")"><ion-icon name="log-out-outline"></ion-icon>Đăng suất</a>
                            </div>
                        </div>
                    </div>
                }



            </div>


        </div>

        <div id="Banner">
            <div class="box-left">

                <h2>Khách SẠN HUYỀN BÍ</h2>
                <p>Feel like home</p>

            </div>



        </div>


        <div id="Products">

            @RenderBody()

        </div>


        <div id="footer" class="">
            <div class="box">
                <div class="logo">
                    <img src="~/Content/images/logo-remov.png" />
                    <p></p>
                </div>
            </div>

            <div class="box">
                <h3>Members</h3>
                <ul class="quick-menu">
                    <div class="item">
                        
                    </div>
                </ul>
            </div>



        </div>

    </div>


    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script src="~/Scripts/MyJs/MyJs.js"></script>
    <script></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>